CONTIKI_PROJECT = coap-actuator
all: $(CONTIKI_PROJECT)
CONTIKI = ../../../



MODULES_REL += ./resources
include $(CONTIKI)/Makefile.dir-variables
MODULES += $(CONTIKI_NG_APP_LAYER_DIR)/coap

include $(CONTIKI)/Makefile.include
